name: dinet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.13.0
  - torchvision=0.14.0
  - torchaudio=0.13.0
  - pytorch-cuda=11.6
  - pip
  - pip:
    - opencv_python==4.6.0.66
    - numpy==1.16.6
    - python_speech_features==0.6
    - resampy==0.2.2
    - scipy==1.5.4
    - tensorflow==1.15.2
    - gdown==4.6.0 